server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/avinashweb/spring-cloud-config/tree/master/primary-config-store
          search-paths:
           - '*service'



