server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/avinashweb/spring-cloud-config
          search-paths:
           - 'primary-config-store/*service'
